### ISSUE TITLE
Enum issue

### ISSUE THREAD

**Issue by karniv00l** [patmood/pocketbase-typegen#21]
Hi there,

I've just tried `v1.1.0`, great job! 

But there's a small issue with generating enums, keys are equal to the values which in some cases will result in syntax error, e.g.:

```ts
export enum MyEnum {
	some value = "some value",
}
```

Not sure about the convention though, I use both `SomeValue` and `SOME_VALUE`: https://www.typescriptlang.org/docs/handbook/enums.html

**Comment by patmood** [comment]
Good point about spaces! Looks like symbols have the same issue. I think this can be mostly worked around by quoting the names like this:

```typescript
export enum EverythingSelectFieldOptions {
	"optionA" = "optionA",
	"OptionA" = "OptionA",
	"optionB" = "optionB",
	"optionC" = "optionC",
	"option with space" = "option with space",
	"sy?mb@!$" = "sy?mb@!$",
}
```
Then you reference it like `EverythingSelectFieldOptions["option with space"]`

The original reason to avoid transforming the name was because you can have 2 similar names with different casing, eg `optionA` and `OptionA`.

Since they need to be escaped for symbols anyway, I'm inclined to just leave the space in there. Does that sound reasonable?

**Comment by karniv00l** [comment]
Yeah, I guess that will work for all cases
