### ISSUE TITLE
Type fields are order sensitive

### ISSUE THREAD

**Issue by einarpersson** [patmood/pocketbase-typegen#77]
**Describe the bug**
If I go into the Pocketbase Admin UI, opens a collection definition and reorder the fields then:
1. No migration file is created by Pocketbase
2. Types by `pocketbase-typegen` are changed 

This feels inconsistent. Either the order of fields should somehow be able to be commited to source (i.e. migrations) which also is reflected in types, OR order of fields are considered just a UI matter and then it should affect neither migrations nor types.

Suggestion (s):
- Always order type fields in alphabetical order
OR
- Provide a flag for doing so (`eg --sort`)

**Versions**
pocketbase-typegen version: `1.1.9`
pocketbase version: `0.17.6`

**Comment by patmood** [comment]
Thanks for flagging this! Right now the ordering matches the pocketbase
schema, which is stored as data in the db (separate from the db schema).

Like you said, the order is just a UI concern. I didn’t even know you could
reorder it in the UI, but wouldn’t it be more organised to have your types
match what’s in the admin UI?

Rather than forcing a convention (eg alphabetical), I think it’s simpler to
follow the ordering in the pb schema.

Are there any issues with having the types update after reordering?

**Comment by einarpersson** [comment]
Consider this case:

A team of developers are working on an application with `pocketbase` and `pocketbase-typegen`. One of the developers changes the order of some fields in his/her UI, which causes the corresponding generated types to change. This is pushed to the main branch. However, this change is not communicated through any migrations. So when another developer pulls the changes and sees that the types have been reordered, he/she has to A) remember that this needs manual work B) go into the UI and manually reorder the fields so that it matches the types. If this is not done, there will be a mismatch when this developer tries to generate types using `pocketbase-typegen`

Perhaps this problem is rather on the Pocketbase side. Where is the field order persisted? Reordering does not generate a migration as far as I can tell. Maybe it should either not be possible to change the order, or it should result in some kind of migration.

**Comment by patmood** [comment]
Ah yeah that’s a great point and a valid issue.  I’ll update to sort the
fields so they’re stable. Thanks for the clarification
