### ISSUE TITLE
Allow use of union types instead of enums

### ISSUE THREAD

**Issue by jchadwick** [patmood/pocketbase-typegen#98]
**FEATURE REQUEST - NOT A BUG**

I kinda despise enums; I find I rarely actually need them.  I strongly prefer union types over enums, and would really like the generated types to be able to include them.

In other words, instead of:

**current**
```typescript
export enum EntityVisibilityOptions {
	"public" = "public",
	"private" = "private",
}
export type EntityRecord = {
	visibility: EntityVisibilityOptions
}
```

I would strongly prefer:

**new**
```typescript
export type EntityVisibilityOptions = "public" | "private"

export type EntityRecord = {
	visibility: EntityVisibilityOptions
}
```

Given this would be a breaking change, I expect this would be a CLI flag rather than actually changing the current behavior.

**Comment by patmood** [comment]
I actually prefer union types too. A while back I made the call to go with enums because it generates an object too. Say you have a select input in the UI, you could use the object to render the options and it would update automatically with the types.

Similar to the pocketbase philosophy, I'd like to keep the API as small and simple as possible and not add options for stylistic reasons. (type vs interface is a similar personal preference)

What I would suggest in your project is creating a new type file that re-exports the generated file, but adds your own overrides. Eg:
```typescript
// Utility type to extract enum values as a union
type EnumToUnion<E> = E[keyof E];

// Creating a union type from the enum
type EntityVisibility = EnumToUnion<typeof EntityVisibilityOptions>;
```

**Comment by jchadwick** [comment]
I agree it's nice to have the list of values to code against.  In those cases I use a const array, like this:

```typescript
const Values = ["one", "two", "three"] as const

type Value = typeof Values[number]
```

Then you have the best of both worlds!

**Comment by jchadwick** [comment]
I see you closed this.  Should I assume you do not intend to implement?

**Comment by jchadwick** [comment]
> ```ts
> // Utility type to extract enum values as a union
> type EnumToUnion<E> = E[keyof E];
> 
> // Creating a union type from the enum
> type EntityVisibility = EnumToUnion<typeof EntityVisibilityOptions>;
> ```

This suggestion doesn't actually work:  https://www.typescriptlang.org/play?#code/PTAEFUBcEsBtsgT1EgDgUxQe1OgHpAE4CGAxpLgHYCuAtqAG7GzXoDOoxHxo1l0WSgCg0mAKI1aAFSzh+ggDxiAfKAC8oMQG0A1ukRYAZpoC6AbiFD0k0ADVobaACM4CRAHlUMQRwDeQ0EDQACJUaid4UmD1ELCI6CiAGgCg0MJoJkh0aI00jOIs4KEAX0sQUABhQnQC6EoAc05eeUoURAxQQ0IsekgAC0xrOhF2zHtHF3gkGIk6GTkBSgVRIzsHZ1ckT29KNmULIVIfCgZ1ybcALjWJzeRcuMjgoA
